### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by 775397252** [Beckschen/TransUNet#12]
hello,i meet a error when i run ` python train.py --dataset Synapse --vit_name R50-ViT-B_16`
Error is as follows:
```
Traceback (most recent call last):
  File "train.py", line 91, in <module>
    net.load_from(weights=np.load(config_vit.pretrained_path))
  File "D:\Python\papers\TransUNet\networks\vit_seg_modeling.py", line 429, in load_from
    unit.load_from(weights, n_block=uname)
  File "D:\Python\papers\TransUNet\networks\vit_seg_modeling.py", line 192, in load_from
    query_weight = np2th(weights[pjoin(ROOT, ATTENTION_Q, "kernel")]).view(self.hidden_size, self.hidden_size).t()
  File "C:\ProgramData\Anaconda3\envs\transnet\lib\site-packages\numpy\lib\npyio.py", line 260, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'Transformer/encoderblock_0\\MultiHeadDotProductAttention_1/query\\kernel is not a file in the archive'
```
env is corrent.and i use win10 and download `R50+ViT-B_16.npz` model in the right place.can you help me ?

**Comment by Beckschen** [comment]
It seems that you are not successfully access the key in the pretrained weight. 
Could you please just replace line 192 of vit_seg_modeling.py:
query_weight = np2th(weights[pjoin(ROOT, ATTENTION_Q, "kernel")]).view(self.hidden_size, self.hidden_size).t()
with
query_weight = np2th(weights["Transformer/encoderblock_0/MultiHeadDotProductAttention_1/query/kernel"]).view(self.hidden_size, self.hidden_size).t()

If do so and there is no bug in line 192, I guess it is the problem that running on windows. 

Let me know if I was wrong. Thanks.

**Comment by lisherlock** [comment]
> hello,i meet a error when i run ` python train.py --dataset Synapse --vit_name R50-ViT-B_16`
> Error is as follows:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 91, in <module>
>     net.load_from(weights=np.load(config_vit.pretrained_path))
>   File "D:\Python\papers\TransUNet\networks\vit_seg_modeling.py", line 429, in load_from
>     unit.load_from(weights, n_block=uname)
>   File "D:\Python\papers\TransUNet\networks\vit_seg_modeling.py", line 192, in load_from
>     query_weight = np2th(weights[pjoin(ROOT, ATTENTION_Q, "kernel")]).view(self.hidden_size, self.hidden_size).t()
>   File "C:\ProgramData\Anaconda3\envs\transnet\lib\site-packages\numpy\lib\npyio.py", line 260, in __getitem__
>     raise KeyError("%s is not a file in the archive" % key)
> KeyError: 'Transformer/encoderblock_0\\MultiHeadDotProductAttention_1/query\\kernel is not a file in the archive'
> ```
> 
> env is corrent.and i use win10 and download `R50+ViT-B_16.npz` model in the right place.can you help me ?

It works in Unbuntu1804, but still can't work in win10.

**Comment by lisherlock** [comment]
> hello,i meet a error when i run ` python train.py --dataset Synapse --vit_name R50-ViT-B_16`
> Error is as follows:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 91, in <module>
>     net.load_from(weights=np.load(config_vit.pretrained_path))
>   File "D:\Python\papers\TransUNet\networks\vit_seg_modeling.py", line 429, in load_from
>     unit.load_from(weights, n_block=uname)
>   File "D:\Python\papers\TransUNet\networks\vit_seg_modeling.py", line 192, in load_from
>     query_weight = np2th(weights[pjoin(ROOT, ATTENTION_Q, "kernel")]).view(self.hidden_size, self.hidden_size).t()
>   File "C:\ProgramData\Anaconda3\envs\transnet\lib\site-packages\numpy\lib\npyio.py", line 260, in __getitem__
>     raise KeyError("%s is not a file in the archive" % key)
> KeyError: 'Transformer/encoderblock_0\\MultiHeadDotProductAttention_1/query\\kernel is not a file in the archive'
> ```
> 
> env is corrent.and i use win10 and download `R50+ViT-B_16.npz` model in the right place.can you help me ?

It works in Ubuntu1804, but still can't work in win10.

**Comment by YUUUCC** [comment]
> It seems that you are not successfully access the key in the pretrained weight.
> Could you please just replace line 192 of vit_seg_modeling.py:
> query_weight = np2th(weights[pjoin(ROOT, ATTENTION_Q, "kernel")]).view(self.hidden_size, self.hidden_size).t()
> with
> query_weight = np2th(weights["Transformer/encoderblock_0/MultiHeadDotProductAttention_1/query/kernel"]).view(self.hidden_size, self.hidden_size).t()
> 
> If do so and there is no bug in line 192, I guess it is the problem that running on windows.
> 
> Let me know if I was wrong. Thanks.

It still can't work in win10, Is there any other way to solve this problem?

**Comment by YUUUCC** [comment]
> It seems that you are not successfully access the key in the pretrained weight.
> Could you please just replace line 192 of vit_seg_modeling.py:
> query_weight = np2th(weights[pjoin(ROOT, ATTENTION_Q, "kernel")]).view(self.hidden_size, self.hidden_size).t()
> with
> query_weight = np2th(weights["Transformer/encoderblock_0/MultiHeadDotProductAttention_1/query/kernel"]).view(self.hidden_size, self.hidden_size).t()
> 
> If do so and there is no bug in line 192, I guess it is the problem that running on windows.
> 
> Let me know if I was wrong. Thanks.

Line 77 of vit_seg_modeling_resnet_skip.py has tihs problem, too. Is there anything I can do?

**Comment by cwpl** [comment]
> > It seems that you are not successfully access the key in the pretrained weight.
> > Could you please just replace line 192 of vit_seg_modeling.py:
> > query_weight = np2th(weights[pjoin(ROOT, ATTENTION_Q, "kernel")]).view(self.hidden_size, self.hidden_size).t()
> > with
> > query_weight = np2th(weights["Transformer/encoderblock_0/MultiHeadDotProductAttention_1/query/kernel"]).view(self.hidden_size, self.hidden_size).t()
> > If do so and there is no bug in line 192, I guess it is the problem that running on windows.
> > Let me know if I was wrong. Thanks.
> 
> Line 77 of vit_seg_modeling_resnet_skip.py has tihs problem, too. Is there anything I can do?

Hi，Have you solved the problem？

**Comment by cwpl** [comment]
@YUUUCC

**Comment by liyiersan** [comment]
> It seems that you are not successfully access the key in the pretrained weight.
> Could you please just replace line 192 of vit_seg_modeling.py:
> query_weight = np2th(weights[pjoin(ROOT, ATTENTION_Q, "kernel")]).view(self.hidden_size, self.hidden_size).t()
> with
> query_weight = np2th(weights["Transformer/encoderblock_0/MultiHeadDotProductAttention_1/query/kernel"]).view(self.hidden_size, self.hidden_size).t()
> 
> If do so and there is no bug in line 192, I guess it is the problem that running on windows.
> 
> Let me know if I was wrong. Thanks.


@775397252  @YUUUCC  @cwpl 
I found a better way to solve this. That is :

1. Create a new file path_util.py in directory networks.

   ```python
   from os.path import join
   from os.path import normpath
   import platform
   
   def pjoin(path, *paths):
       p = join(path, *paths)
       if platform.system() == "Windows":
           return normpath(p).replace('\\','/')
       else:
           return p
   ```

2.  Import  pjoin in file vit_seg_modeling_resnet_skip.py and vit_seg_modeling.py

   ```python
   from .path_util import pjoin
   ```

   

3. And this may due to '\\' is not recognized by numpy when using np.load to load a npz file.

**Comment by dyvdyvaass** [comment]
https://blog.csdn.net/qq_37278761/article/details/121493618

**Comment by skywords** [comment]
thanks
