### ISSUE TITLE
cannot、

### ISSUE THREAD

**Issue by yyxun** [Beckschen/TransUNet#22]

**Comment by yyxun** [comment]
Hi there!
Thank you for your innovative work.
I cannot find the 'R50-ViT-L_16' pretrained model on google's vit_models website. So I want to know how to train the 'R50-ViT-L_16' network.
Looking forward to your reply.
Thank you!

**Comment by Beckschen** [comment]
Hello, sorry for the late reply. Please nudge me in the email if you have urgent question next time.

You raise a good question that Google didn't provide the pretrained weight for "R50-ViT-L_16". We instead took a compromise solution that loading the individual ResNet50 weight and ViT-L_16 weight provided by Google. However, this might not be the optimal solution as the weights of two module are not generated from end2end training.

Thanks! Let me know if you have other quesitons.

**Comment by a313071162** [comment]
> Hi there!
> Thank you for your innovative work.
> I cannot find the 'R50-ViT-L_16' pretrained model on google's vit_models website. So I want to know how to train the 'R50-ViT-L_16' network.
> Looking forward to your reply.
> Thank you!

Have you solved this problem?

> Hello, sorry for the late reply. Please nudge me in the email if you have urgent question next time.
> 
> You raise a good question that Google didn't provide the pretrained weight for "R50-ViT-L_16". We instead took a compromise solution that loading the individual ResNet50 weight and the ViT-L_16 weight provided by Google. However, this might not be the optimal solution as the weights of the two modules are not generated from end2end training.
> 
> Thanks! Let me know if you have other questions.

Hi,
How do you combine? I tried some methods and there was an error. Can you tell me in detail?
Thank you!!!

**Comment by fabihabushra** [comment]
@Beckschen Can you please elaborate how your compromise solution works? I have kept the pretrained weights ViT-L_16.npz and R50+ViT-B_16.npz in the ../model/vit_checkpoint/imagenet21k/ directory. When I try to train the model using --vit_name 'R50-ViT-L_16', it gives the following error:

Traceback (most recent call last):
  File "/content/project_TransUNet/TransUNet/train.py", line 96, in <module>
    net.load_from(weights=np.load(config_vit.pretrained_path))
  File "/content/project_TransUNet/TransUNet/networks/vit_seg_modeling.py", line 406, in load_from
    self.transformer.embeddings.patch_embeddings.weight.copy_(converted_weights)
RuntimeError: The size of tensor a (1024) must match the size of tensor b (3) at non-singleton dimension 1

I have additionally printed to see the shapes of the weight and patch embeddings which gives: 
Shape of loaded weights: (16, 16, 3, 1024)
Shape of converted weights: torch.Size([1024, 3, 16, 16])       # np2th(weights["embedding/kernel"], conv=True)
Shape of patch_embeddings.weight: torch.Size([1024, 1024, 1, 1])

So, I am not sure how to train the R50-ViT-L_16 model since there is a shape mismatch.

**Comment by Yanweijians** [comment]
Hi@fabihabushra ,have you solved this problem, can you share it, my email 2900351468@qq.com, thank you very much

**Comment by LiuChengAkina** [comment]
@Yanweijians @fabihabushra ,,have you solved this problem, can you share it, my email [qliucheng@mail.ustc.edu.cn], thank you very much
