### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by StevenAZy** [Beckschen/TransUNet#26]
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    trainer[dataset_name](args, net, snapshot_path)
  File "/home/lichangyong/Code/TransUNet/trainer.py", line 57, in trainer_synapse
    loss_dice = dice_loss(outputs, label_batch, softmax=True)
  File "/home/lichangyong/.pyenv/versions/pytorch_gpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lichangyong/Code/TransUNet/utils.py", line 43, in forward
    class_wise_dice.append(1.0 - dice.item())
RuntimeError: CUDA error: device-side assert triggered

**Comment by andife** [comment]
Hi,
I think I had a similar error message. The reason for this was the names, or the numerical values of my labels. 
Maybe look https://github.com/facebookresearch/SymbolicMathematics/issues/2 
You should find several github issues looking for the expression "RuntimeError: CUDA error: device-side assert triggered".

**Comment by StevenAZy** [comment]
> Hi,
> I think I had a similar error message. The reason for this was the names, or the numerical values of my labels.
> Maybe look [facebookresearch/SymbolicMathematics#2](https://github.com/facebookresearch/SymbolicMathematics/issues/2)
> You should find several github issues looking for the expression "RuntimeError: CUDA error: device-side assert triggered".

**Comment by SM-93** [comment]
I had a similar problem, I was training the model with 13 classes instead of 9 (8 organs + background) so I had to change the num_classes in the dataset_config (train.py)  to 14. Maybe you are also training with 13 classes.

**Comment by AllenPiaoHong** [comment]
> I had a similar problem, I was training the model with 13 classes instead of 9 (8 organs + background) so I had to change the num_classes in the dataset_config (train.py) to 14. Maybe you are also training with 13 classes.

Hi, have you fixed the problem now. I also change the num_classes in train.py. But it doesn't work.

**Comment by StevenAZy** [comment]
> > I had a similar problem, I was training the model with 13 classes instead of 9 (8 organs + background) so I had to change the num_classes in the dataset_config (train.py) to 14. Maybe you are also training with 13 classes.
> 
> Hi, have you fixed the problem now. I also change the num_classes in train.py. But it doesn't work.

I changed the num_classes value to 14. The code can run successfully.

**Comment by rameses666** [comment]
I think the reason is the value of your label.Check that.

**Comment by JAYCHOU2020** [comment]
> > > I had a similar problem, I was training the model with 13 classes instead of 9 (8 organs + background) so I had to change the num_classes in the dataset_config (train.py) to 14. Maybe you are also training with 13 classes.
> > 
> > 
> > Hi, have you fixed the problem now. I also change the num_classes in train.py. But it doesn't work.
> 
> I changed the num_classes value to 14. The code can run successfully.

my dataset class is 1 so I set numclass=2 but it also report the error ,even I set numclass=3 it not work

**Comment by buhuiya** [comment]
有人解决了吗
