### ISSUE TITLE
Running the test.py.

### ISSUE THREAD

**Issue by stefenmax** [Beckschen/TransUNet#43]
Traceback (most recent call last):
  File "test.py", line 122, in <module>
    net.load_state_dict(torch.load(snapshot))
  File "/home/jdj/anaconda3/envs/trans/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
 Missing key(s) in state_dict: 
A lot of keys were merged, could u please tell me how to fix it? 
Thanks!

**Comment by cwpl** [comment]
@stefenmax   Have you solved the problem?  Thanks.

**Comment by wangyueying666** [comment]
Have you solved the problem?  I also couldn't run the test.py with a keyerror

**Comment by a821836620** [comment]
Have you solved the problem? I also couldn't run the test.py with a key error

**Comment by a821836620** [comment]
I have solved the problem. It‘s because multiple GPUs are used in training. so
Modify test.py
parser.add_argument('--use_gpu', type=bool,
                    default=True, help='In training use multiple GPU')

net = ViT_seg(config_vit, img_size=args.img_size, num_classes=config_vit.n_classes).cuda()
## join
if args.use_gpu:
    net = torch.nn.DataParallel(net).cuda()
##

**Comment by SeptemberNightRain** [comment]
> I have solved the problem. It‘s because multiple GPUs are used in training. so Modify test.py
> 
> ```
> parser.add_argument('--use_gpu', type=bool,
>                     default=True, help='In training use multiple GPU')
> 
> net = ViT_seg(config_vit, img_size=args.img_size, num_classes=config_vit.n_classes).cuda()
> ## join
> if args.use_gpu:
>     net = torch.nn.DataParallel(net).cuda()
> ##
> ```

Thank you for your solution !
