### ISSUE TITLE
Error running test.py

### ISSUE THREAD

**Issue by fmd233** [Beckschen/TransUNet#62]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch_1.8\lib\site-packages\ml_collections\config_dict\config_dict.py", line 883, in __getitem__
    field = self._fields[key]
KeyError: 'skip_channels'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch_1.8\lib\site-packages\ml_collections\config_dict\config_dict.py", line 807, in __getattr__
    return self[attribute]
  File "D:\Anaconda3\envs\pytorch_1.8\lib\site-packages\ml_collections\config_dict\config_dict.py", line 889, in __getitem__
    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
KeyError: "'skip_channels'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/admin/Desktop/project_TransUNet/TransUNet/test.py", line 118, in <module>
    net = ViT_seg(config_vit, img_size=args.img_size, num_classes=config_vit.n_classes).cuda()
  File "C:\Users\admin\Desktop\project_TransUNet\TransUNet\networks\vit_seg_modeling.py", line 378, in __init__
    self.decoder = DecoderCup(config)
  File "C:\Users\admin\Desktop\project_TransUNet\TransUNet\networks\vit_seg_modeling.py", line 344, in __init__
    skip_channels = self.config.skip_channels
  File "D:\Anaconda3\envs\pytorch_1.8\lib\site-packages\ml_collections\config_dict\config_dict.py", line 809, in __getattr__
    raise AttributeError(e)
AttributeError: "'skip_channels'"

could u please tell me how to fix it?
Thanks!

**Comment by 15260297222** [comment]
The same problem,can you ask me how you resolve it that time?

**Comment by 15260297222** [comment]
The same problem,can you tell me how you resolve it that time?

**Comment by GivenAward** [comment]
Try this
`skip_channels = self.config.skip_channels`
to
`skip_channels = [512, 256, 128, 64]`

**Comment by GivenAward** [comment]
Try this
`parser.add_argument('--vit_name', type=str, default='ViT-B_16', help='select one vit model')`
to
`parser.add_argument('--vit_name', type=str, default='R50-ViT-B_16', help='select one vit model')`
