### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by mehmetariftasli** [Beckschen/TransUNet#63]
Trying to train on the synapse dataset

Namespace(base_lr=0.01, batch_size=24, dataset='Synapse', deterministic=1, exp='TU_Synapse224', img_size=224, is_pre
train=True, list_dir='./lists/lists_Synapse', max_epochs=150, max_iterations=30000, n_gpu=1, n_skip=3, num_classes=9
, root_path='../data/Synapse/train_npz', seed=1234, vit_name='R50-ViT-B_16', vit_patches_size=16)
The length of train set is: 2211
93 iterations per epoch. 13950 max iterations
  0%|                                         | 0/150 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    trainer[dataset_name](args, net, snapshot_path)
  File "C:\Users\arif1\PycharmProjects\pythonProject\TransUNet\trainer.py", line 52, in trainer_synapse
    for i_batch, sampled_batch in enumerate(trainloader):
  File "C:\Users\arif1\anaconda3\envs\pythonProject\trans\lib\site-packages\torch\utils\data\dataloader.py", line 27
9, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\arif1\anaconda3\envs\pythonProject\trans\lib\site-packages\torch\utils\data\dataloader.py", line 71
9, in __init__
    w.start()
  File "C:\Users\arif1\anaconda3\envs\pythonProject\trans\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\arif1\anaconda3\envs\pythonProject\trans\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\arif1\anaconda3\envs\pythonProject\trans\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\arif1\anaconda3\envs\pythonProject\trans\lib\multiprocessing\popen_spawn_win32.py", line 89, in __i
nit__
    reduction.dump(process_obj, to_child)
  File "C:\Users\arif1\anaconda3\envs\pythonProject\trans\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'trainer_synapse.<locals>.worker_init_fn'
PS C:\Users\arif1\PycharmProjects\pythonProject\TransUNet> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\arif1\anaconda3\envs\pythonProject\trans\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\arif1\anaconda3\envs\pythonProject\trans\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by mehmetariftasli** [comment]
fixed it by setting the num_workers to 0, windows does not support it i guess

**Comment by Bigearth6** [comment]
> fixed it by setting the num_workers to 0, windows does not support it i guess

which file to set?
